### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by KevDoy** [halo-goldsrc/HaloGS#4]
The Half-Life version you're using (Anniversary, CD, Steam, etc): [xash3d-fwgs](https://github.com/FWGS/xash3d-fwgs)
Your Windows or other OS version: macOS 
Which Halo GoldSrc Build: Alpha 1
Did you make any modifications to the build?: No
Details of the issue: The game loads, however weapons don't behave as expected. Needler is more like the weapon it's based on. Shotgun has more shots than expected between reloads.
How to reproduce the issue: Load up HaloGS on Xash3D, load into a map and try out the weapons.

**Comment by KevDoy** [comment]
Tested these issues on Xash3D FWGS on Windows and the Needler functions as expected. Appears to be a Linux/macOS issue.

**Comment by KevDoy** [comment]
#3 tested and does not fix the issue. However, updating compiled linux binaries may fix this issue per @jokurino

**Comment by jokurino** [comment]
#7 Might fix some stuff for Linux plarforms.

**Comment by KevDoy** [comment]
Current workaround is to launch Half-Life with Proton on Linux. No workaround for Xash3D or macOS yet.

**Comment by sabianroberts** [comment]
TPPS does not actively target Xash3D due to the legality of the code used, but if any of our mods happen to work on Xash3D anyway, that's awesome. The Linux port is finished now so closing for now.
